# Generated by Django 3.1 on 2020-08-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک یکتا')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('title', 'status'),
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='متن مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
