# Generated by Django 3.1 on 2020-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200827_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstruct',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_important',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='خبر ویژه'),
        ),
        migrations.AddField(
            model_name='article',
            name='ro_titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رو تیتر'),
        ),
    ]
