# Generated by Django 3.1 on 2020-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200906_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='خبر ویژه'),
        ),
    ]
